name       : wireguard-tools
version    : 1.0.20210315
release    : 5
source     :
    - https://git.zx2c4.com/wireguard-tools/snapshot/wireguard-tools-1.0.20210315.tar.xz : af001d5492be6bf58ef0bebe04b446b6f50eb53e1226fab679cc34af40733a22
license    : GPL-2.0-only
component  : network.util
summary    : Required tools for WireGuard, such as wg(8) and wg-quick(8)
description: |
    This supplies the main userspace tooling for using and configuring WireGuard tunnels, including the wg(8) and wg-quick(8) utilities.
rundeps    :
    - iproute2
environment: |
    export WITH_WGQUICK=yes
    export WITH_SYSTEMDUNITS=yes
setup      : |
    %apply_patches
build      : |
    %make -C src
install    : |
    %make_install -C src

    # Remove empty directories
    rm -r $installdir/etc
