name       : wireguard-tools
version    : 1.0.20200513
release    : 1
source     :
    - https://git.zx2c4.com/wireguard-tools/snapshot/wireguard-tools-1.0.20200513.tar.xz : e73409a9fb8c90506db241d1e1a4e7372a60dbfa400e37f4ab2fd70a92ba495f
license    : GPL-2.0-only
component  : network.util
summary    : Required tools for WireGuard, such as wg(8) and wg-quick(8)
description: |
    This supplies the main userspace tooling for using and configuring WireGuard tunnels, including the wg(8) and wg-quick(8) utilities.
environment: |
    export WITH_WGQUICK=yes
    export WITH_SYSTEMDUNITS=yes
build      : |
    %make -C src
install    : |
    %make_install -C src

    # Remove empty directories
    rm -r $installdir/etc
