name       : wireguard-tools
version    : 1.0.20200820
release    : 3
source     :
    - https://git.zx2c4.com/wireguard-tools/snapshot/wireguard-tools-1.0.20200820.tar.xz : 7735a04c68fffb101a10a67e3bd97a171f2b8eb47e9ddce2be68eb6538b013d0
license    : GPL-2.0-only
component  : network.util
summary    : Required tools for WireGuard, such as wg(8) and wg-quick(8)
description: |
    This supplies the main userspace tooling for using and configuring WireGuard tunnels, including the wg(8) and wg-quick(8) utilities.
rundeps    :
    - iproute2
environment: |
    export WITH_WGQUICK=yes
    export WITH_SYSTEMDUNITS=yes
build      : |
    %make -C src
install    : |
    %make_install -C src

    # Remove empty directories
    rm -r $installdir/etc
